"""Generate + write ``.khimaira/context.yaml`` — the #66 dynamic-context cache.

Write-side counterpart to ``khimaira.context_inject`` (the read-side
``resolve_context``).  Two DISTINCT responsibilities, kept separate by design
(architect's hard boundary — the frequent regen must never trigger source
writes):

* ``generate_context_yaml`` / ``_write_context_yaml`` — the FREQUENT regen
  path: cheap, AUTO-only, MANUAL-preserving.  Emits the frozen-v1 schema the
  read-side consumes.
* ``_scaffold_missing_docs`` — the RARE source-write path: creates a
  per-feature ``CLAUDE.md`` skeleton.  NEVER called by the frequent regen.

Frozen v1 schema (MUST stay in lockstep with
``khimaira.context_inject.resolve_context``)::

    head_hash: <git HEAD sha when generated>
    generated_at: "<YYYY-MM-DD>"
    classes:
      architecture: {hint, pointers, dep_graph_note?}
      bugfix:       {hint, pointers, framework?}
      coordination: {hint, pointers}
      simple:       {hint, pointers}
    manual:                       # human-curated; preserved verbatim on regen
      architecture: {hint, pointers}
      ...
    features_without_claude_md: [<feature name>, ...]

The read-side merges MANUAL -> AUTO -> BUILTIN (most-valuable first) and caps at
12, so AUTO ``pointers`` are RANKED by dep-graph centrality and capped here too.
``feature_docs`` is intentionally NOT emitted: frozen-v1 pre-expands per-feature
CLAUDE.md paths directly into ``pointers`` (the read-side ignores feature_docs).
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import subprocess
from datetime import date
from pathlib import Path
from typing import Any, Callable

from scarlet.analyzer.features import scan_features
from scarlet.analyzer.imports import FeatureGraph, build_feature_graph
from scarlet.analyzer.project import analyze_project
from scarlet.generator.claude_md import build_claude_md

# The four prompt classes the read-side classifier emits. Keep in lockstep with
# khimaira.hooks.user_prompt_submit._classify_prompt + context_inject._BUILTIN_DEFAULTS.
CLASSES: tuple[str, ...] = ("architecture", "bugfix", "coordination", "simple")

# Mirror khimaira.context_inject._MAX_POINTERS — AUTO pointers ranked + capped.
_MAX_POINTERS: int = 12

_CONTEXT_DIR: str = ".khimaira"
_CONTEXT_FILE: str = "context.yaml"

_HEADER: str = (
    "# Auto-generated by Scarlet — khimaira dynamic context injection (#66).\n"
    "# AUTO sections regenerate; edit ONLY the `manual:` section (preserved on regen).\n"
)

# Project-agnostic hints carried by a PRESENT context.yaml. (The read-side has
# its own built-in defaults for a missing/corrupt file.)
_HINTS: dict[str, str] = {
    "architecture": "Read these before proposing structure or refactoring.",
    "bugfix": "Reproduce first; check the failing file + its tests + recent git history for that path.",
    "coordination": "Full project context for roster/delegation work.",
    "simple": "",
}

_GENERIC_BUGFIX_POINTERS: list[str] = [
    "Run the failing test for the touched file",
    "git log -p --follow <file>",
]

_ROOT_DOC_CANDIDATES: tuple[str, ...] = (
    "CLAUDE.md",
    "AGENTS.md",
    "README.md",
    "IMPLEMENTATION_PLAN.md",
    "tasks/BUILD-PLAN.md",
    "ARCHITECTURE.md",
)


def _git_head(project_root: Path) -> str:
    """Current git HEAD sha, or "" if not a git repo / git unavailable (fail-open)."""
    try:
        out = subprocess.run(
            ["git", "-C", str(project_root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def _root_doc_pointers(project_root: Path) -> list[str]:
    """Root-level docs that actually exist (ecosystem-agnostic — CLAUDE.md/AGENTS.md/...)."""
    return [c for c in _ROOT_DOC_CANDIDATES if (project_root / c).is_file()]


def _in_degree(graph: FeatureGraph | None) -> dict[str, int]:
    """feature-name -> count of features importing it (centrality proxy)."""
    if graph is None:
        return {}
    degree: dict[str, int] = {f: 0 for f in graph.features}
    for _from_feature, to_feature in graph.edges:
        degree[to_feature] = degree.get(to_feature, 0) + 1
    return degree


def _safe_feature_graph(project_root: Path) -> FeatureGraph | None:
    try:
        return build_feature_graph(project_root)
    except Exception:
        return None


def _dep_graph_note(graph: FeatureGraph | None) -> str:
    """Prose hub/circular-dep/deep-import summary for the architecture class."""
    if graph is None or not graph.features:
        return ""
    degree = _in_degree(graph)
    hubs = [(name, deg) for name, deg in sorted(degree.items(), key=lambda kv: kv[1], reverse=True) if deg]
    edge_set = set(graph.edges)
    circulars = sorted({tuple(sorted((a, b))) for (a, b) in graph.edges if (b, a) in edge_set and a != b})

    lines: list[str] = ["Key dependency hubs (from Scarlet dep-graph):"]
    for name, deg in hubs[:5]:
        lines.append(f"- {name}: imported by {deg} feature(s)")
    for a, b in circulars[:5]:
        lines.append(f"- {a} <-> {b}: circular dep (flag before refactoring either)")
    if graph.deep_imports:
        lines.append(
            f"Deep import count: {len(graph.deep_imports)} (bypass feature barrel — flagged tech debt)"
        )
    return "\n".join(lines)


def _detect_framework(project_root: Path) -> str:
    """e.g. "Next.js / Redux Toolkit / Vitest" — best-effort, "" on any failure."""
    try:
        manifest = analyze_project(project_root)
    except Exception:
        return ""
    parts = [
        getattr(manifest, "project_type", "") or "",
        getattr(manifest, "state_management", "") or "",
        getattr(manifest, "test_framework", "") or "",
    ]
    return " / ".join(p for p in parts if p)


def generate_context_yaml(
    project_root: str | Path,
    analyzer: Callable[..., Any] | None = None,
) -> dict[str, Any]:
    """Build the frozen-v1 ``context.yaml`` dict for a project (PURE — no disk write).

    ``analyzer`` is the optional LLM dependency-injection hook (Scarlet-semantic
    SUGGESTED tier); when ``None`` hints stay generic — no LLM call.  Reserved so
    the caller (khimaira, which holds creds) opts in; Scarlet never imports an LLM.
    """
    root = Path(project_root).resolve()
    features = scan_features(root)
    graph = _safe_feature_graph(root)
    degree = _in_degree(graph)

    # Architecture pointers: root docs + top-N feature CLAUDE.md ranked by
    # centrality, capped at _MAX_POINTERS. Pre-expanded concrete paths (no globs).
    arch_pointers: list[str] = _root_doc_pointers(root)
    docs = sorted(
        (f for f in features if f.has_claude_md),
        key=lambda f: degree.get(f.name, 0),
        reverse=True,
    )
    for feat in docs:
        if len(arch_pointers) >= _MAX_POINTERS:
            break
        try:
            rel = Path(feat.path).resolve().relative_to(root)
            arch_pointers.append(f"{rel}/CLAUDE.md")
        except ValueError:
            arch_pointers.append(f"{feat.path}/CLAUDE.md")
    arch_pointers = arch_pointers[:_MAX_POINTERS]

    classes: dict[str, Any] = {
        "architecture": {"hint": _HINTS["architecture"], "pointers": arch_pointers},
        "bugfix": {"hint": _HINTS["bugfix"], "pointers": list(_GENERIC_BUGFIX_POINTERS)},
        "coordination": {"hint": _HINTS["coordination"], "pointers": _root_doc_pointers(root)[:4]},
        "simple": {"hint": _HINTS["simple"], "pointers": []},
    }
    note = _dep_graph_note(graph)
    if note:
        classes["architecture"]["dep_graph_note"] = note
    framework = _detect_framework(root)
    if framework:
        classes["bugfix"]["framework"] = framework

    return {
        "head_hash": _git_head(root),
        "generated_at": date.today().isoformat(),
        "classes": classes,
        "manual": {c: {"hint": "", "pointers": []} for c in CLASSES},
        "features_without_claude_md": [f.name for f in features if not f.has_claude_md],
    }


def features_without_claude_md(project_root: str | Path) -> list[str]:
    """Feature names that exist but lack a ``CLAUDE.md`` (the auto-fill-loop trigger source)."""
    return [f.name for f in scan_features(Path(project_root).resolve()) if not f.has_claude_md]


def _classes_fingerprint(data: dict[str, Any]) -> str:
    """Stable hash of the AUTO ``classes`` content (excludes head_hash/generated_at).

    Used for idempotent-skip: a regen whose AUTO content is unchanged should not
    rewrite the file (avoids pointlessly invalidating the read-side mtime cache).
    """
    return hashlib.sha256(
        json.dumps(data.get("classes", {}), sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()


def _write_context_yaml(path: str | Path, data: dict[str, Any]) -> None:
    """Write ``data`` to ``path`` via ruamel round-trip — FREQUENT regen path.

    * Idempotent: skip the write entirely if the AUTO ``classes`` content is
      unchanged from the existing file.
    * MANUAL-preserve: an existing ``manual:`` section is kept VERBATIM (with its
      comments) — only the AUTO keys are replaced.  Never clobbers human edits.
    * Atomic: write to ``context.yaml.tmp`` then ``os.replace``.

    ruamel (not pyyaml) is mandatory: pyyaml strips the manual-section comments
    on round-trip; the read-side uses pyyaml safe_load (read-only) which reads
    ruamel-emitted YAML fine.
    """
    from ruamel.yaml import YAML

    path = Path(path)
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)

    existing: Any = None
    if path.is_file():
        try:
            existing = yaml.load(path.read_text(encoding="utf-8"))
        except Exception:
            existing = None

    # Idempotent: AUTO content unchanged -> no write (head_hash drift is tolerated;
    # SessionStart / the other regen triggers reconcile staleness).
    if isinstance(existing, dict) and _classes_fingerprint(existing) == _classes_fingerprint(data):
        return

    new_file = existing is None
    if isinstance(existing, dict):
        # Preserve the existing manual: subtree + comments; replace AUTO keys only.
        out: Any = existing
        out["head_hash"] = data["head_hash"]
        out["generated_at"] = data["generated_at"]
        out["classes"] = data["classes"]
        out["features_without_claude_md"] = data["features_without_claude_md"]
        if "manual" not in out:
            out["manual"] = data["manual"]
    else:
        out = data

    path.parent.mkdir(parents=True, exist_ok=True)
    buf = io.StringIO()
    if new_file:
        buf.write(_HEADER)
    yaml.dump(out, buf)

    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(buf.getvalue(), encoding="utf-8")
    os.replace(tmp, path)


def refresh_context_yaml(project_root: str | Path, analyzer: Callable[..., Any] | None = None) -> Path:
    """Convenience: generate + write ``.khimaira/context.yaml``. Returns the path.

    This is the FREQUENT regen entry point shared by the 4 callers (attach /
    observer-signal / post-commit / ``khimaira context refresh``).  AUTO-only —
    it does NOT scaffold docs (that is the separate rare source-write path).
    """
    root = Path(project_root).resolve()
    data = generate_context_yaml(root, analyzer=analyzer)
    target = root / _CONTEXT_DIR / _CONTEXT_FILE
    _write_context_yaml(target, data)
    return target


def _scaffold_missing_docs(project_root: str | Path, feature_path: str | Path) -> str | None:
    """Create ``<feature_path>/CLAUDE.md`` if missing — RARE source-write path.

    Reuses Scarlet's ``build_claude_md`` (consistent skeleton + the keyed
    ``<!-- BEGIN MANUAL: key -->`` markers used elsewhere) rather than a bespoke
    template.  NEW-ONLY / idempotent: returns the created path, or ``None`` if a
    CLAUDE.md already exists (never overwrites).
    """
    root = Path(project_root).resolve()
    feat = Path(feature_path).resolve()
    claude_md = feat / "CLAUDE.md"
    if claude_md.exists():
        return None
    build_claude_md(root, feat, write=True)
    return str(claude_md)
