"""Project metadata layer.

Each langgraph project chimera-monitor inspects gets an internal cache
file at ~/.cache/chimera/monitor/<project>.yaml. The user never writes
or sees this file — it's auto-generated by the daemon on first encounter,
using chimera's own LLM tooling to read the project's source and
synthesize a richer architecture description than AST alone can provide.

Cache layers below the diagram render:
  1. AST extraction (raw nodes, edges, basic shapes)         ← always present
  2. Cache yaml (roles, labels, hierarchy, summary)          ← present after first scan
  3. Live runtime data (current_node, status, step)          ← per-poll

The merge happens in `merge.py`. The cache file schema is in `schema.py`.
"""

from .cache import CACHE_DIR, cache_path, is_stale, load, save
from .merge import enrich_topology
from .schema import GraphMetadata, NodeMetadata, ProjectMetadata

__all__ = [
    "CACHE_DIR",
    "GraphMetadata",
    "NodeMetadata",
    "ProjectMetadata",
    "cache_path",
    "enrich_topology",
    "is_stale",
    "load",
    "save",
]
